language: cpp
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - llvm-toolchain-precise-3.9
    packages:
    - g++-6
#    - clang-3.9
compiler:
- g++
#- clang++
env:
- COMPILER=g++-6
#- COMPILER=clang-3.9
before_install:
- cd thirdparty/googletest/googletest
- cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=$COMPILER .
- make
- cd -
- mkdir build
- cd build
install:
- cmake -DCMAKE_INSTALL_PREFIX=install -DENABLE_TEST=ON -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=$COMPILER .. 
- make
- make install
script:
- ctest
