language: cpp
dist: trusty
sudo: false
matrix:
  include:
  - compiler: g++
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER=g++-6
  - compiler: clang++
    addons:
      apt:
        sourtces:
        - llvm-toolchain-precise-3.8
        packages:
        - clang-3.8
    env:
    - COMPILER=clang-3.8
before_install:
- cd thirdparty/googletest/googletest
- cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=$COMPILER .
- make
- cd -
- mkdir build
- cd build
install:
- cmake -DCMAKE_INSTALL_PREFIX=install -DENABLE_TEST=ON -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=$COMPILER .. 
- make
- make install
script:
- ctest
