[package]
name = "gussing_game"
version = "0.1.0"
authors = ["FORNO <forno@xmaho.link>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.6"